EXAMPLES = [
    {
        "id": "basic_shapes",
        "name": "Basic Shapes",
        "description": "Circle, Square, and Text with FadeIn sequence",
        "graph": {
            "id": "example-basic-shapes",
            "name": "Basic Shapes",
            "nodes": [
                {
                    "id": "node-1",
                    "type": "Circle",
                    "position": {"x": 100, "y": 100},
                    "data": {
                        "type": "Circle",
                        "radius": "1.0",
                        "color": "#58C4DD",
                        "fill_opacity": "0.5",
                        "position": "[-3, 0, 0]",
                    },
                },
                {
                    "id": "node-2",
                    "type": "Square",
                    "position": {"x": 100, "y": 350},
                    "data": {
                        "type": "Square",
                        "side_length": "2.0",
                        "color": "#83C167",
                        "fill_opacity": "0.5",
                        "position": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-3",
                    "type": "Text",
                    "position": {"x": 100, "y": 600},
                    "data": {
                        "type": "Text",
                        "text": "Hello Manim!",
                        "font_size": "48.0",
                        "color": "#FFFFFF",
                        "position": "[3, 0, 0]",
                    },
                },
                {
                    "id": "node-4",
                    "type": "FadeIn",
                    "position": {"x": 450, "y": 100},
                    "data": {
                        "type": "FadeIn",
                        "run_time": "1.0",
                        "shift": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-5",
                    "type": "FadeIn",
                    "position": {"x": 450, "y": 350},
                    "data": {
                        "type": "FadeIn",
                        "run_time": "1.0",
                        "shift": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-6",
                    "type": "Write",
                    "position": {"x": 450, "y": 600},
                    "data": {
                        "type": "Write",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "node-7",
                    "type": "Sequence",
                    "position": {"x": 800, "y": 350},
                    "data": {
                        "type": "Sequence",
                        "wait_time": "0.5",
                    },
                },
            ],
            "edges": [
                {"id": "e1", "source": "node-1", "target": "node-4", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e2", "source": "node-2", "target": "node-5", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e3", "source": "node-3", "target": "node-6", "sourceHandle": "text", "targetHandle": "mobject"},
                {"id": "e4", "source": "node-4", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e5", "source": "node-5", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e6", "source": "node-6", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim3"},
            ],
            "settings": {},
        },
    },
    {
        "id": "pythagorean",
        "name": "Pythagorean Theorem",
        "description": "Rearrangement proof using TransformInPlace (rotate + move in one node)",
        "graph": {
            "id": "example-pythagorean",
            "name": "Pythagorean Theorem",
            "nodes": [
                # ── Camera zoom ──
                {
                    "id": "cam-zoom",
                    "type": "PythonCode",
                    "position": {"x": 100, "y": 10},
                    "data": {
                        "type": "PythonCode",
                        "name": "cam_zoom",
                        "code": "self.set_camera_orientation(zoom=0.75)",
                    },
                },
                # ── Title ──
                {
                    "id": "title",
                    "type": "Text",
                    "position": {"x": 100, "y": 60},
                    "data": {
                        "type": "Text",
                        "name": "title",
                        "text": "Pythagorean Theorem",
                        "font_size": "56.0",
                        "color": "#FFFFFF",
                        "position": "[0, 4.5, 0]",
                    },
                },
                {
                    "id": "show-title",
                    "type": "Show",
                    "position": {"x": 400, "y": 60},
                    "data": {"type": "Show", "name": "show_title"},
                },
                # ── Source right triangle (a=1.5, b=2.0, c=2.5) ──
                {
                    "id": "tri",
                    "type": "RightTriangle",
                    "position": {"x": 100, "y": 200},
                    "data": {
                        "type": "RightTriangle",
                        "name": "triangle",
                        "base": "1.5",
                        "height": "2.0",
                        "color": "#FFFFFF",
                        "fill_opacity": "0.08",
                        "stroke_width": "3.0",
                        "position": "[0, 3.0, 0]",
                    },
                },
                # ── Phase 1: Create triangle ──
                {
                    "id": "create-tri",
                    "type": "Create",
                    "position": {"x": 400, "y": 100},
                    "data": {"type": "Create", "name": "create_tri", "run_time": "1.5"},
                },
                # ── Phase 2: Squares from edges ──
                {
                    "id": "sq-a",
                    "type": "SquareFromEdge",
                    "position": {"x": 400, "y": 230},
                    "data": {
                        "type": "SquareFromEdge",
                        "name": "sq_a",
                        "run_time": "1.0",
                        "color": "#58C4DD",
                        "fill_opacity": "0.25",
                    },
                },
                {
                    "id": "sq-c",
                    "type": "SquareFromEdge",
                    "position": {"x": 400, "y": 340},
                    "data": {
                        "type": "SquareFromEdge",
                        "name": "sq_c",
                        "run_time": "1.0",
                        "color": "#FC6255",
                        "fill_opacity": "0.25",
                    },
                },
                {
                    "id": "sq-b",
                    "type": "SquareFromEdge",
                    "position": {"x": 400, "y": 450},
                    "data": {
                        "type": "SquareFromEdge",
                        "name": "sq_b",
                        "run_time": "1.0",
                        "color": "#83C167",
                        "fill_opacity": "0.25",
                    },
                },
                {
                    "id": "grp-squares",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 340},
                    "data": {"type": "AnimationGroup", "name": "grp_squares", "run_time": "1.5", "lag_ratio": "0.3"},
                },
                # ── Phase 3: Side labels (LineLabel) ──
                {
                    "id": "lbl-a",
                    "type": "LineLabel",
                    "position": {"x": 100, "y": 450},
                    "data": {
                        "type": "LineLabel",
                        "name": "lbl_a",
                        "text": "a",
                        "font_size": "72.0",
                        "color": "#58C4DD",
                        "position": "0.5",
                        "offset": "0.5",
                    },
                },
                {
                    "id": "lbl-c",
                    "type": "LineLabel",
                    "position": {"x": 100, "y": 530},
                    "data": {
                        "type": "LineLabel",
                        "name": "lbl_c",
                        "text": "c",
                        "font_size": "72.0",
                        "color": "#FC6255",
                        "position": "0.5",
                        "offset": "0.5",
                    },
                },
                {
                    "id": "lbl-b",
                    "type": "LineLabel",
                    "position": {"x": 100, "y": 610},
                    "data": {
                        "type": "LineLabel",
                        "name": "lbl_b",
                        "text": "b",
                        "font_size": "72.0",
                        "color": "#83C167",
                        "position": "0.5",
                        "offset": "0.5",
                    },
                },
                {
                    "id": "write-a",
                    "type": "Write",
                    "position": {"x": 400, "y": 530},
                    "data": {"type": "Write", "name": "write_a", "run_time": "0.8"},
                },
                {
                    "id": "write-c",
                    "type": "Write",
                    "position": {"x": 400, "y": 580},
                    "data": {"type": "Write", "name": "write_c", "run_time": "0.8"},
                },
                {
                    "id": "write-b",
                    "type": "Write",
                    "position": {"x": 400, "y": 630},
                    "data": {"type": "Write", "name": "write_b", "run_time": "0.8"},
                },
                {
                    "id": "grp-labels",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 580},
                    "data": {"type": "AnimationGroup", "name": "grp_labels", "run_time": "1.0", "lag_ratio": "0.0"},
                },
                # ── Proof frame + inner c² square ──
                {
                    "id": "proof-outer",
                    "type": "Polyline",
                    "position": {"x": 100, "y": 750},
                    "data": {
                        "type": "Polyline",
                        "name": "proof_frame",
                        "points": "[[-1.75,-1.75,0],[1.75,-1.75,0],[1.75,1.75,0],[-1.75,1.75,0]]",
                        "closed": "true",
                        "color": "#FFFFFF",
                        "fill_opacity": "0.0",
                        "stroke_width": "2.0",
                        "position": "[3.5, -1.0, 0]",
                    },
                },
                {
                    "id": "proof-inner",
                    "type": "Polyline",
                    "position": {"x": 100, "y": 830},
                    "data": {
                        "type": "Polyline",
                        "name": "proof_c2",
                        "points": "[[-0.25,-1.75,0],[1.75,-0.25,0],[0.25,1.75,0],[-1.75,0.25,0]]",
                        "closed": "true",
                        "color": "#FC6255",
                        "fill_opacity": "0.15",
                        "stroke_width": "2.0",
                        "position": "[3.5, -1.0, 0]",
                    },
                },
                # ── Phase 4: TransformInPlace × 4 (copy=true) ──
                # Each node rotates a copy of the triangle and places it at the target
                # Old approach needed: 4 RightTriangles + 4 Vec3 + 4 MoveTo + 4 Rotate + 2 Groups = 18 nodes
                # New approach: 1 RightTriangle + 4 TransformInPlace + 1 Group = 6 nodes
                {
                    "id": "tip-1",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 780},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_1",
                        "copy": True,
                        "angle": "0",
                        "target": "[2.5, -1.75, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-2",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 850},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_2",
                        "copy": True,
                        "angle": "90",
                        "target": "[4.25, -2.0, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-3",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 920},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_3",
                        "copy": True,
                        "angle": "180",
                        "target": "[4.5, -0.25, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-4",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 990},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_4",
                        "copy": True,
                        "angle": "-90",
                        "target": "[2.75, 0.0, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "grp-arrange",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 880},
                    "data": {"type": "AnimationGroup", "name": "grp_arrange", "run_time": "1.5", "lag_ratio": "0.2"},
                },
                # ── Phase 5: Show frame + c² square ──
                {
                    "id": "create-frame",
                    "type": "Create",
                    "position": {"x": 400, "y": 1100},
                    "data": {"type": "Create", "name": "create_frame", "run_time": "1.0"},
                },
                {
                    "id": "fadein-inner",
                    "type": "FadeIn",
                    "position": {"x": 400, "y": 1160},
                    "data": {"type": "FadeIn", "name": "fadein_inner", "run_time": "1.0", "shift": "[0, 0, 0]"},
                },
                {
                    "id": "grp-proof",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 1130},
                    "data": {"type": "AnimationGroup", "name": "grp_proof", "run_time": "1.0", "lag_ratio": "0.0"},
                },
                # ── Phase 6: proof labels ──
                {
                    "id": "plbl-a",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1100},
                    "data": {
                        "type": "MathTex",
                        "name": "plbl_a",
                        "tex": "a",
                        "font_size": "48.0",
                        "color": "#58C4DD",
                        "position": "[2.5, -3.1, 0]",
                    },
                },
                {
                    "id": "plbl-b",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1160},
                    "data": {
                        "type": "MathTex",
                        "name": "plbl_b",
                        "tex": "b",
                        "font_size": "48.0",
                        "color": "#83C167",
                        "position": "[1.35, -1.75, 0]",
                    },
                },
                {
                    "id": "plbl-c",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1220},
                    "data": {
                        "type": "MathTex",
                        "name": "plbl_c",
                        "tex": "c",
                        "font_size": "48.0",
                        "color": "#FC6255",
                        "position": "[2.75, -1.5, 0]",
                    },
                },
                {
                    "id": "write-pa",
                    "type": "Write",
                    "position": {"x": 400, "y": 1240},
                    "data": {"type": "Write", "name": "write_pa", "run_time": "0.6"},
                },
                {
                    "id": "write-pb",
                    "type": "Write",
                    "position": {"x": 400, "y": 1290},
                    "data": {"type": "Write", "name": "write_pb", "run_time": "0.6"},
                },
                {
                    "id": "write-pc",
                    "type": "Write",
                    "position": {"x": 400, "y": 1340},
                    "data": {"type": "Write", "name": "write_pc", "run_time": "0.6"},
                },
                {
                    "id": "grp-plabels",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 1290},
                    "data": {"type": "AnimationGroup", "name": "grp_plabels", "run_time": "0.8", "lag_ratio": "0.0"},
                },
                # ── Phase 7: c² label + equation ──
                {
                    "id": "lbl-c2",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1380},
                    "data": {
                        "type": "MathTex",
                        "name": "lbl_c2",
                        "tex": "c^2",
                        "font_size": "72.0",
                        "color": "#FC6255",
                        "position": "[3.5, -1.0, 0]",
                    },
                },
                {
                    "id": "equation",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1460},
                    "data": {
                        "type": "MathTex",
                        "name": "equation",
                        "tex": "a^2 + b^2 = c^2",
                        "font_size": "72.0",
                        "color": "#FFFF00",
                        "position": "[0, -3.8, 0]",
                    },
                },
                {
                    "id": "write-c2",
                    "type": "Write",
                    "position": {"x": 400, "y": 1380},
                    "data": {"type": "Write", "name": "write_c2", "run_time": "0.8"},
                },
                {
                    "id": "write-eq",
                    "type": "Write",
                    "position": {"x": 400, "y": 1460},
                    "data": {"type": "Write", "name": "write_eq", "run_time": "1.5"},
                },
                # ── Left frame (a²+b² arrangement) ──
                {
                    "id": "proof-outer-L",
                    "type": "Polyline",
                    "position": {"x": 100, "y": 1500},
                    "data": {
                        "type": "Polyline",
                        "name": "proof_frame_L",
                        "points": "[[-1.75,-1.75,0],[1.75,-1.75,0],[1.75,1.75,0],[-1.75,1.75,0]]",
                        "closed": "true",
                        "color": "#FFFFFF",
                        "fill_opacity": "0.0",
                        "stroke_width": "2.0",
                        "position": "[-3.5, -1.0, 0]",
                    },
                },
                {
                    "id": "sq-a2",
                    "type": "Polyline",
                    "position": {"x": 100, "y": 1560},
                    "data": {
                        "type": "Polyline",
                        "name": "sq_a2",
                        "points": "[[-0.75,-0.75,0],[0.75,-0.75,0],[0.75,0.75,0],[-0.75,0.75,0]]",
                        "closed": "true",
                        "color": "#58C4DD",
                        "fill_opacity": "0.2",
                        "stroke_width": "2.0",
                        "position": "[-4.5, 0.0, 0]",
                    },
                },
                {
                    "id": "sq-b2",
                    "type": "Polyline",
                    "position": {"x": 100, "y": 1620},
                    "data": {
                        "type": "Polyline",
                        "name": "sq_b2",
                        "points": "[[-1.0,-1.0,0],[1.0,-1.0,0],[1.0,1.0,0],[-1.0,1.0,0]]",
                        "closed": "true",
                        "color": "#83C167",
                        "fill_opacity": "0.2",
                        "stroke_width": "2.0",
                        "position": "[-2.75, -1.75, 0]",
                    },
                },
                # ── Phase 8: TransformInPlace × 4 for a²+b² (copy=true) ──
                {
                    "id": "tip-L1",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 1500},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_L1",
                        "copy": True,
                        "angle": "0",
                        "target": "[-4.5, -1.75, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-L2",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 1570},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_L2",
                        "copy": True,
                        "angle": "180",
                        "target": "[-4.5, -1.75, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-L3",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 1640},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_L3",
                        "copy": True,
                        "angle": "90",
                        "target": "[-2.75, 0.0, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "tip-L4",
                    "type": "TransformInPlace",
                    "position": {"x": 400, "y": 1710},
                    "data": {
                        "type": "TransformInPlace",
                        "name": "tip_L4",
                        "copy": True,
                        "angle": "-90",
                        "target": "[-2.75, 0.0, 0]",
                        "run_time": "1.5",
                    },
                },
                {
                    "id": "grp-arrange-L",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 1600},
                    "data": {"type": "AnimationGroup", "name": "grp_arrange_L", "run_time": "1.5", "lag_ratio": "0.2"},
                },
                # ── Phase 9: Show left frame + a²/b² squares + labels ──
                {
                    "id": "create-frame-L",
                    "type": "Create",
                    "position": {"x": 400, "y": 1800},
                    "data": {"type": "Create", "name": "create_frame_L", "run_time": "0.8"},
                },
                {
                    "id": "fadein-a2",
                    "type": "FadeIn",
                    "position": {"x": 400, "y": 1860},
                    "data": {"type": "FadeIn", "name": "fadein_a2", "run_time": "0.8", "shift": "[0, 0, 0]"},
                },
                {
                    "id": "fadein-b2",
                    "type": "FadeIn",
                    "position": {"x": 400, "y": 1920},
                    "data": {"type": "FadeIn", "name": "fadein_b2", "run_time": "0.8", "shift": "[0, 0, 0]"},
                },
                {
                    "id": "lbl-a2",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1800},
                    "data": {
                        "type": "MathTex",
                        "name": "lbl_a2",
                        "tex": "a^2",
                        "font_size": "60.0",
                        "color": "#58C4DD",
                        "position": "[-4.5, 0.0, 0]",
                    },
                },
                {
                    "id": "lbl-b2",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1860},
                    "data": {
                        "type": "MathTex",
                        "name": "lbl_b2",
                        "tex": "b^2",
                        "font_size": "60.0",
                        "color": "#83C167",
                        "position": "[-2.75, -1.75, 0]",
                    },
                },
                {
                    "id": "write-a2",
                    "type": "Write",
                    "position": {"x": 400, "y": 1980},
                    "data": {"type": "Write", "name": "write_a2", "run_time": "0.6"},
                },
                {
                    "id": "write-b2",
                    "type": "Write",
                    "position": {"x": 400, "y": 2040},
                    "data": {"type": "Write", "name": "write_b2", "run_time": "0.6"},
                },
                {
                    "id": "plbl-a-L",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1930},
                    "data": {
                        "type": "MathTex",
                        "name": "plbl_a_L",
                        "tex": "a",
                        "font_size": "42.0",
                        "color": "#58C4DD",
                        "position": "[-5.55, 0.0, 0]",
                    },
                },
                {
                    "id": "plbl-b-L",
                    "type": "MathTex",
                    "position": {"x": 100, "y": 1990},
                    "data": {
                        "type": "MathTex",
                        "name": "plbl_b_L",
                        "tex": "b",
                        "font_size": "42.0",
                        "color": "#83C167",
                        "position": "[-2.75, -3.1, 0]",
                    },
                },
                {
                    "id": "write-pa-L",
                    "type": "Write",
                    "position": {"x": 400, "y": 2100},
                    "data": {"type": "Write", "name": "write_pa_L", "run_time": "0.6"},
                },
                {
                    "id": "write-pb-L",
                    "type": "Write",
                    "position": {"x": 400, "y": 2160},
                    "data": {"type": "Write", "name": "write_pb_L", "run_time": "0.6"},
                },
                {
                    "id": "grp-proof-L",
                    "type": "AnimationGroup",
                    "position": {"x": 700, "y": 1900},
                    "data": {"type": "AnimationGroup", "name": "grp_proof_L", "run_time": "1.2", "lag_ratio": "0.15"},
                },
                # ── Sequence ──
                {
                    "id": "seq",
                    "type": "Sequence",
                    "position": {"x": 1050, "y": 600},
                    "data": {"type": "Sequence", "name": "sequence", "wait_time": "0.5"},
                },
            ],
            "edges": [
                # Title → Show
                {"id": "eT1", "source": "title", "target": "show-title", "sourceHandle": "text", "targetHandle": "mobject"},
                # Triangle → Create
                {"id": "e1", "source": "tri", "target": "create-tri", "sourceHandle": "shape", "targetHandle": "mobject"},
                # Triangle sides → SquareFromEdge
                {"id": "e2", "source": "tri", "target": "sq-a", "sourceHandle": "side_1", "targetHandle": "mobject"},
                {"id": "e3", "source": "tri", "target": "sq-c", "sourceHandle": "side_2", "targetHandle": "mobject"},
                {"id": "e4", "source": "tri", "target": "sq-b", "sourceHandle": "side_3", "targetHandle": "mobject"},
                # SquareFromEdge → AnimationGroup
                {"id": "e5", "source": "sq-a", "target": "grp-squares", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e6", "source": "sq-c", "target": "grp-squares", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e7", "source": "sq-b", "target": "grp-squares", "sourceHandle": "animation", "targetHandle": "anim3"},
                # Triangle sides → LineLabels
                {"id": "e8", "source": "tri", "target": "lbl-a", "sourceHandle": "side_1", "targetHandle": "line"},
                {"id": "e9", "source": "tri", "target": "lbl-c", "sourceHandle": "side_2", "targetHandle": "line"},
                {"id": "e10", "source": "tri", "target": "lbl-b", "sourceHandle": "side_3", "targetHandle": "line"},
                # Labels → Write
                {"id": "e11", "source": "lbl-a", "target": "write-a", "sourceHandle": "label", "targetHandle": "mobject"},
                {"id": "e12", "source": "lbl-c", "target": "write-c", "sourceHandle": "label", "targetHandle": "mobject"},
                {"id": "e13", "source": "lbl-b", "target": "write-b", "sourceHandle": "label", "targetHandle": "mobject"},
                # Write → AnimationGroup
                {"id": "e14", "source": "write-a", "target": "grp-labels", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e15", "source": "write-c", "target": "grp-labels", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e16", "source": "write-b", "target": "grp-labels", "sourceHandle": "animation", "targetHandle": "anim3"},
                # Triangle → 4 TransformInPlace (each with copy=true)
                {"id": "e17", "source": "tri", "target": "tip-1", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e18", "source": "tri", "target": "tip-2", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e19", "source": "tri", "target": "tip-3", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e20", "source": "tri", "target": "tip-4", "sourceHandle": "shape", "targetHandle": "mobject"},
                # TransformInPlace → AnimationGroup
                {"id": "e21", "source": "tip-1", "target": "grp-arrange", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e22", "source": "tip-2", "target": "grp-arrange", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e23", "source": "tip-3", "target": "grp-arrange", "sourceHandle": "animation", "targetHandle": "anim3"},
                {"id": "e24", "source": "tip-4", "target": "grp-arrange", "sourceHandle": "animation", "targetHandle": "anim4"},
                # Outer frame → Create, Inner c² → FadeIn
                {"id": "e25", "source": "proof-outer", "target": "create-frame", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e26", "source": "proof-inner", "target": "fadein-inner", "sourceHandle": "shape", "targetHandle": "mobject"},
                # Create + FadeIn → AnimationGroup
                {"id": "e27", "source": "create-frame", "target": "grp-proof", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e28", "source": "fadein-inner", "target": "grp-proof", "sourceHandle": "animation", "targetHandle": "anim2"},
                # Proof labels → Write
                {"id": "e29", "source": "plbl-a", "target": "write-pa", "sourceHandle": "tex", "targetHandle": "mobject"},
                {"id": "e30", "source": "plbl-b", "target": "write-pb", "sourceHandle": "tex", "targetHandle": "mobject"},
                {"id": "e31", "source": "plbl-c", "target": "write-pc", "sourceHandle": "tex", "targetHandle": "mobject"},
                # Write → AnimationGroup (proof labels)
                {"id": "e32", "source": "write-pa", "target": "grp-plabels", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e33", "source": "write-pb", "target": "grp-plabels", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e34", "source": "write-pc", "target": "grp-plabels", "sourceHandle": "animation", "targetHandle": "anim3"},
                # c² label + equation → Write
                {"id": "e35", "source": "lbl-c2", "target": "write-c2", "sourceHandle": "tex", "targetHandle": "mobject"},
                {"id": "e36", "source": "equation", "target": "write-eq", "sourceHandle": "tex", "targetHandle": "mobject"},
                # Triangle → 4 TransformInPlace (left, a²+b² arrangement)
                {"id": "eL1", "source": "tri", "target": "tip-L1", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "eL2", "source": "tri", "target": "tip-L2", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "eL3", "source": "tri", "target": "tip-L3", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "eL4", "source": "tri", "target": "tip-L4", "sourceHandle": "shape", "targetHandle": "mobject"},
                # TransformInPlace → AnimationGroup (left)
                {"id": "eL5", "source": "tip-L1", "target": "grp-arrange-L", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "eL6", "source": "tip-L2", "target": "grp-arrange-L", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "eL7", "source": "tip-L3", "target": "grp-arrange-L", "sourceHandle": "animation", "targetHandle": "anim3"},
                {"id": "eL8", "source": "tip-L4", "target": "grp-arrange-L", "sourceHandle": "animation", "targetHandle": "anim4"},
                # Left frame → Create, a²/b² squares → FadeIn
                {"id": "eL9", "source": "proof-outer-L", "target": "create-frame-L", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "eL10", "source": "sq-a2", "target": "fadein-a2", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "eL11", "source": "sq-b2", "target": "fadein-b2", "sourceHandle": "shape", "targetHandle": "mobject"},
                # a²/b² labels → Write
                {"id": "eL12", "source": "lbl-a2", "target": "write-a2", "sourceHandle": "tex", "targetHandle": "mobject"},
                {"id": "eL13", "source": "lbl-b2", "target": "write-b2", "sourceHandle": "tex", "targetHandle": "mobject"},
                # a/b side labels (left) → Write
                {"id": "eL12b", "source": "plbl-a-L", "target": "write-pa-L", "sourceHandle": "tex", "targetHandle": "mobject"},
                {"id": "eL12c", "source": "plbl-b-L", "target": "write-pb-L", "sourceHandle": "tex", "targetHandle": "mobject"},
                # Left proof elements → AnimationGroup
                {"id": "eL14", "source": "create-frame-L", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "eL15", "source": "fadein-a2", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "eL16", "source": "fadein-b2", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim3"},
                {"id": "eL17", "source": "write-a2", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim4"},
                {"id": "eL18", "source": "write-b2", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim5"},
                {"id": "eL19", "source": "write-pa-L", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim6"},
                {"id": "eL20", "source": "write-pb-L", "target": "grp-proof-L", "sourceHandle": "animation", "targetHandle": "anim7"},
                # All phases → Sequence (10 phases)
                {"id": "e40", "source": "create-tri", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e41", "source": "grp-squares", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e42", "source": "grp-labels", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim3"},
                {"id": "e43", "source": "grp-arrange", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim4"},
                {"id": "e44", "source": "grp-proof", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim5"},
                {"id": "e45", "source": "grp-plabels", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim6"},
                {"id": "e47", "source": "write-c2", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim7"},
                {"id": "e48", "source": "grp-arrange-L", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim8"},
                {"id": "e49", "source": "grp-proof-L", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim9"},
                {"id": "e50", "source": "write-eq", "target": "seq", "sourceHandle": "animation", "targetHandle": "anim10"},
            ],
            "settings": {},
        },
    },
    {
        "id": "eigenvectors",
        "name": "Eigenvectors",
        "description": "Matrix transform with vectors showing eigenvector behavior",
        "graph": {
            "id": "example-eigenvectors",
            "name": "Eigenvectors",
            "nodes": [
                {
                    "id": "node-1",
                    "type": "NumberPlane",
                    "position": {"x": 100, "y": 100},
                    "data": {
                        "type": "NumberPlane",
                        "x_range_min": "-5.0",
                        "x_range_max": "5.0",
                        "y_range_min": "-5.0",
                        "y_range_max": "5.0",
                        "position": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-2",
                    "type": "Vector",
                    "position": {"x": 100, "y": 400},
                    "data": {
                        "type": "Vector",
                        "direction": "[2, 1, 0]",
                        "color": "#58C4DD",
                    },
                },
                {
                    "id": "node-3",
                    "type": "Vector",
                    "position": {"x": 100, "y": 600},
                    "data": {
                        "type": "Vector",
                        "direction": "[1, 2, 0]",
                        "color": "#FC6255",
                    },
                },
                {
                    "id": "node-4",
                    "type": "Show",
                    "position": {"x": 450, "y": 100},
                    "data": {"type": "Show"},
                },
                {
                    "id": "node-5",
                    "type": "FadeIn",
                    "position": {"x": 450, "y": 400},
                    "data": {"type": "FadeIn", "run_time": "1.0", "shift": "[0, 0, 0]"},
                },
                {
                    "id": "node-6",
                    "type": "FadeIn",
                    "position": {"x": 450, "y": 600},
                    "data": {"type": "FadeIn", "run_time": "1.0", "shift": "[0, 0, 0]"},
                },
                {
                    "id": "node-7",
                    "type": "Sequence",
                    "position": {"x": 750, "y": 350},
                    "data": {"type": "Sequence", "wait_time": "0.5"},
                },
            ],
            "edges": [
                {"id": "e1", "source": "node-1", "target": "node-4", "sourceHandle": "plane", "targetHandle": "mobject"},
                {"id": "e2", "source": "node-2", "target": "node-5", "sourceHandle": "vector", "targetHandle": "mobject"},
                {"id": "e3", "source": "node-3", "target": "node-6", "sourceHandle": "vector", "targetHandle": "mobject"},
                {"id": "e4", "source": "node-4", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e5", "source": "node-5", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e6", "source": "node-6", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim3"},
            ],
            "settings": {},
        },
    },
    {
        "id": "fourier",
        "name": "Parametric Curves",
        "description": "Parametric sine and cosine curves on coordinate axes",
        "graph": {
            "id": "example-fourier",
            "name": "Parametric Curves",
            "nodes": [
                {
                    "id": "node-1",
                    "type": "Axes",
                    "position": {"x": 100, "y": 100},
                    "data": {
                        "type": "Axes",
                        "x_range_min": "-4.0",
                        "x_range_max": "4.0",
                        "y_range_min": "-2.0",
                        "y_range_max": "2.0",
                        "x_length": "10.0",
                        "y_length": "4.0",
                        "position": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-2",
                    "type": "ParametricFunction",
                    "position": {"x": 100, "y": 400},
                    "data": {
                        "type": "ParametricFunction",
                        "code": "import numpy as np\nx = t\ny = np.sin(t)\nz = 0\nreturn [x, y, z]",
                        "t_range_min": "-4",
                        "t_range_max": "4",
                        "color": "#58C4DD",
                        "stroke_width": "3.0",
                        "position": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-3",
                    "type": "ParametricFunction",
                    "position": {"x": 100, "y": 700},
                    "data": {
                        "type": "ParametricFunction",
                        "code": "import numpy as np\nx = t\ny = np.cos(t)\nz = 0\nreturn [x, y, z]",
                        "t_range_min": "-4",
                        "t_range_max": "4",
                        "color": "#FC6255",
                        "stroke_width": "3.0",
                        "position": "[0, 0, 0]",
                    },
                },
                {
                    "id": "node-4",
                    "type": "Show",
                    "position": {"x": 450, "y": 100},
                    "data": {"type": "Show"},
                },
                {
                    "id": "node-5",
                    "type": "Create",
                    "position": {"x": 450, "y": 400},
                    "data": {"type": "Create", "run_time": "2.0"},
                },
                {
                    "id": "node-6",
                    "type": "Create",
                    "position": {"x": 450, "y": 700},
                    "data": {"type": "Create", "run_time": "2.0"},
                },
                {
                    "id": "node-7",
                    "type": "Sequence",
                    "position": {"x": 750, "y": 350},
                    "data": {"type": "Sequence", "wait_time": "0.5"},
                },
            ],
            "edges": [
                {"id": "e1", "source": "node-1", "target": "node-4", "sourceHandle": "axes", "targetHandle": "mobject"},
                {"id": "e2", "source": "node-2", "target": "node-5", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e3", "source": "node-3", "target": "node-6", "sourceHandle": "shape", "targetHandle": "mobject"},
                {"id": "e4", "source": "node-4", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim1"},
                {"id": "e5", "source": "node-5", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim2"},
                {"id": "e6", "source": "node-6", "target": "node-7", "sourceHandle": "animation", "targetHandle": "anim3"},
            ],
            "settings": {},
        },
    },
]


def get_example_list():
    return [{"id": e["id"], "name": e["name"], "description": e["description"]} for e in EXAMPLES]


def get_example_by_id(example_id: str):
    for e in EXAMPLES:
        if e["id"] == example_id:
            return e
    return None
