from .base import NodeBase
from .shapes import CircleNode, SquareNode, RectangleNode, LineNode, TextNode, ArrowNode, TriangleNode, RegularPolygonNode, RightTriangleNode, IsoscelesTriangleNode, LineLabelNode, AngleNode
from .animations import (
    FadeInNode, FadeOutNode, ShowNode, WriteNode, CreateNode,
    MorphNode, RotateNode, ScaleNode, MoveToNode, SequenceNode, AnimationGroupNode,
    # Creation
    UncreateNode, UnwriteNode, DrawBorderThenFillNode, SpiralInNode,
    # Growing
    GrowFromCenterNode, GrowFromPointNode, GrowFromEdgeNode, GrowArrowNode, SpinInFromNothingNode,
    # Indication
    IndicateNode, FlashNode, CircumscribeNode, WiggleNode, ApplyWaveNode, FocusOnNode,
    # Movement
    MoveAlongPathNode,
    # Transform
    ReplacementMorphNode, MorphFromCopyNode, FadeMorphNode,
    MorphMatchingShapesNode, MorphMatchingTexNode, FadeToColorNode, ShrinkToCenterNode,
    # Other
    BroadcastNode, SwapNode,
    SquareFromEdgeNode,
)
from .math import AxesNode, NumberPlaneNode, MathTexNode, VectorNode, DotNode, LinePlotNode, PolylineNode, ParametricFunctionNode, DisplayMatrixNode
from .utilities import JunctionNode, DebugPrintNode, GroupNode, TextCharacterNode, PythonCodeNode, TransformNode, TransformInPlaceNode, ExtractEdgesNode, ExposeParametersNode, GetVertexNode, ImportGraphNode, FunctionDefNode, FunctionCallNode
from .shapes3d import SphereNode, CubeNode, ConeNode, CylinderNode, TorusNode, Axes3DNode
from .camera import (
    SetCameraOrientationNode, MoveCameraNode, ZoomCameraNode,
)
from .math_ops import (
    AddNode, SubtractNode, MultiplyNode, DivideNode, NegateNode,
    NumberNode, Vec3Node,
    RightNode, LeftNode, UpNode, DownNode, OutNode, InNode,
    OriginNode, XNode, YNode, ZNode,
    Vec3SplitNode, Vec3CombineNode,
    Vec3AddNode, Vec3SubtractNode, Vec3ScaleNode, Vec3NegateNode,
    Vec3DotNode, Vec3CrossNode, Vec3LengthNode, Vec3NormalizeNode,
    MatrixNode, MatrixMultiplyNode, MatrixScaleNode,
    MatrixAddNode, MatrixSubtractNode, MatrixInverseNode,
    MatrixTransposeNode, MatrixNegateNode, MatrixDeterminantNode,
    MatrixVecMultiplyNode,
    TranslateMatrixNode, RotateMatrixNode, ScaleMatrixNode, ComposeMatrixNode,
    ColorNode,
)

# Registry of all available node types
NODE_REGISTRY = {
    # Shapes
    "Circle": CircleNode,
    "Square": SquareNode,
    "Rectangle": RectangleNode,
    "Line": LineNode,
    "Text": TextNode,
    "Arrow": ArrowNode,
    "Triangle": TriangleNode,
    "RegularPolygon": RegularPolygonNode,
    "RightTriangle": RightTriangleNode,
    "IsoscelesTriangle": IsoscelesTriangleNode,
    "FadeIn": FadeInNode,
    "FadeOut": FadeOutNode,
    "Show": ShowNode,
    "Write": WriteNode,
    "Create": CreateNode,
    "Morph": MorphNode,
    "Rotate": RotateNode,
    "Scale": ScaleNode,
    "MoveTo": MoveToNode,
    "Sequence": SequenceNode,
    "AnimationGroup": AnimationGroupNode,
    # Creation animations
    "Uncreate": UncreateNode,
    "Unwrite": UnwriteNode,
    "DrawBorderThenFill": DrawBorderThenFillNode,
    "SpiralIn": SpiralInNode,
    # Growing animations
    "GrowFromCenter": GrowFromCenterNode,
    "GrowFromPoint": GrowFromPointNode,
    "GrowFromEdge": GrowFromEdgeNode,
    "GrowArrow": GrowArrowNode,
    "SpinInFromNothing": SpinInFromNothingNode,
    # Indication animations
    "Indicate": IndicateNode,
    "Flash": FlashNode,
    "Circumscribe": CircumscribeNode,
    "Wiggle": WiggleNode,
    "ApplyWave": ApplyWaveNode,
    "FocusOn": FocusOnNode,
    # Movement animations
    "MoveAlongPath": MoveAlongPathNode,
    # Transform animations
    "ReplacementMorph": ReplacementMorphNode,
    "MorphFromCopy": MorphFromCopyNode,
    "FadeMorph": FadeMorphNode,
    "MorphMatchingShapes": MorphMatchingShapesNode,
    "MorphMatchingTex": MorphMatchingTexNode,
    "FadeToColor": FadeToColorNode,
    "ShrinkToCenter": ShrinkToCenterNode,
    # Other animations
    "Broadcast": BroadcastNode,
    "Swap": SwapNode,
    "SquareFromEdge": SquareFromEdgeNode,
    "Axes": AxesNode,
    "NumberPlane": NumberPlaneNode,
    "MathTex": MathTexNode,
    "Vector": VectorNode,
    "Dot": DotNode,
    "DisplayMatrix": DisplayMatrixNode,
    "LinePlot": LinePlotNode,
    "Polyline": PolylineNode,
    "ParametricFunction": ParametricFunctionNode,
    # Utilities
    "Junction": JunctionNode,
    "DebugPrint": DebugPrintNode,
    "Group": GroupNode,
    "TextCharacter": TextCharacterNode,
    "PythonCode": PythonCodeNode,
    "Transform": TransformNode,
    "TransformInPlace": TransformInPlaceNode,
    "ExtractEdges": ExtractEdgesNode,
    "ExposeParameters": ExposeParametersNode,
    "GetVertex": GetVertexNode,
    "ImportGraph": ImportGraphNode,
    "FunctionDef": FunctionDefNode,
    "FunctionCall": FunctionCallNode,
    # Text & Math (additional)
    "LineLabel": LineLabelNode,
    "Angle": AngleNode,
    # 3D Shapes
    "Sphere": SphereNode,
    "Cube": CubeNode,
    "Cone": ConeNode,
    "Cylinder": CylinderNode,
    "Torus": TorusNode,
    "Axes3D": Axes3DNode,
    # Camera
    "SetCameraOrientation": SetCameraOrientationNode,
    "MoveCamera": MoveCameraNode,
    "ZoomCamera": ZoomCameraNode,
    # Math Operations
    "Add": AddNode,
    "Subtract": SubtractNode,
    "Multiply": MultiplyNode,
    "Divide": DivideNode,
    "Number": NumberNode,
    "Vec3": Vec3Node,
    "RIGHT": RightNode,
    "LEFT": LeftNode,
    "UP": UpNode,
    "DOWN": DownNode,
    "OUT": OutNode,
    "IN": InNode,
    "ORIGIN": OriginNode,
    "X": XNode,
    "Y": YNode,
    "Z": ZNode,
    "Vec3Split": Vec3SplitNode,
    "Vec3Combine": Vec3CombineNode,
    "Matrix": MatrixNode,
    "MatrixMultiply": MatrixMultiplyNode,
    "MatrixScale": MatrixScaleNode,
    "TranslateMatrix": TranslateMatrixNode,
    "RotateMatrix": RotateMatrixNode,
    "ScaleMatrix": ScaleMatrixNode,
    "ComposeMatrix": ComposeMatrixNode,
    "Color": ColorNode,
    # Scalar Operations
    "Negate": NegateNode,
    # Vector Operations
    "Vec3Add": Vec3AddNode,
    "Vec3Subtract": Vec3SubtractNode,
    "Vec3Scale": Vec3ScaleNode,
    "Vec3Negate": Vec3NegateNode,
    "Vec3Dot": Vec3DotNode,
    "Vec3Cross": Vec3CrossNode,
    "Vec3Length": Vec3LengthNode,
    "Vec3Normalize": Vec3NormalizeNode,
    # Matrix Operations
    "MatrixAdd": MatrixAddNode,
    "MatrixSubtract": MatrixSubtractNode,
    "MatrixInverse": MatrixInverseNode,
    "MatrixTranspose": MatrixTransposeNode,
    "MatrixNegate": MatrixNegateNode,
    "MatrixDeterminant": MatrixDeterminantNode,
    "MatrixVecMultiply": MatrixVecMultiplyNode,
}

__all__ = [
    "NodeBase",
    "NODE_REGISTRY",
    # Shapes
    "CircleNode",
    "SquareNode",
    "RectangleNode",
    "LineNode",
    "TextNode",
    "ArrowNode",
    "TriangleNode",
    "RegularPolygonNode",
    "RightTriangleNode",
    "IsoscelesTriangleNode",
    "FadeInNode",
    "FadeOutNode",
    "ShowNode",
    "WriteNode",
    "CreateNode",
    "MorphNode",
    "RotateNode",
    "ScaleNode",
    "MoveToNode",
    "SequenceNode",
    "AnimationGroupNode",
    # Creation animations
    "UncreateNode",
    "UnwriteNode",
    "DrawBorderThenFillNode",
    "SpiralInNode",
    # Growing animations
    "GrowFromCenterNode",
    "GrowFromPointNode",
    "GrowFromEdgeNode",
    "GrowArrowNode",
    "SpinInFromNothingNode",
    # Indication animations
    "IndicateNode",
    "FlashNode",
    "CircumscribeNode",
    "WiggleNode",
    "ApplyWaveNode",
    "FocusOnNode",
    # Movement animations
    "MoveAlongPathNode",
    # Transform animations
    "ReplacementMorphNode",
    "MorphFromCopyNode",
    "FadeMorphNode",
    "MorphMatchingShapesNode",
    "MorphMatchingTexNode",
    "FadeToColorNode",
    "ShrinkToCenterNode",
    # Other animations
    "BroadcastNode",
    "SwapNode",
    "SquareFromEdgeNode",
    "AxesNode",
    "NumberPlaneNode",
    "MathTexNode",
    "VectorNode",
    "DotNode",
    "DisplayMatrixNode",
    "LinePlotNode",
    "PolylineNode",
    "ParametricFunctionNode",
    # Utilities
    "JunctionNode",
    "DebugPrintNode",
    "GroupNode",
    "TextCharacterNode",
    "PythonCodeNode",
    "TransformNode",
    "TransformInPlaceNode",
    "ExtractEdgesNode",
    "ExposeParametersNode",
    "GetVertexNode",
    "ImportGraphNode",
    "FunctionDefNode",
    "FunctionCallNode",
    "LineLabelNode",
    "AngleNode",
    # 3D Shapes
    "SphereNode",
    "CubeNode",
    "ConeNode",
    "CylinderNode",
    "TorusNode",
    "Axes3DNode",
    # Camera
    "SetCameraOrientationNode",
    "MoveCameraNode",
    "ZoomCameraNode",
    # Math Operations
    "AddNode",
    "SubtractNode",
    "MultiplyNode",
    "DivideNode",
    "NumberNode",
    "Vec3Node",
    "RightNode",
    "LeftNode",
    "UpNode",
    "DownNode",
    "OutNode",
    "InNode",
    "OriginNode",
    "XNode",
    "YNode",
    "ZNode",
    "Vec3SplitNode",
    "Vec3CombineNode",
    "MatrixNode",
    "MatrixMultiplyNode",
    "MatrixScaleNode",
    "TranslateMatrixNode",
    "RotateMatrixNode",
    "ScaleMatrixNode",
    "ComposeMatrixNode",
    "ColorNode",
    # Scalar Operations
    "NegateNode",
    # Vector Operations
    "Vec3AddNode",
    "Vec3SubtractNode",
    "Vec3ScaleNode",
    "Vec3NegateNode",
    "Vec3DotNode",
    "Vec3CrossNode",
    "Vec3LengthNode",
    "Vec3NormalizeNode",
    # Matrix Operations
    "MatrixAddNode",
    "MatrixSubtractNode",
    "MatrixInverseNode",
    "MatrixTransposeNode",
    "MatrixNegateNode",
    "MatrixDeterminantNode",
    "MatrixVecMultiplyNode",
]
